SET C51INC=C:\Keil_v5\C51\C51\Inc;C:\Keil_v5\C51\C51\Inc\Nuvoton
SET C51LIB=C:\Keil_v5\C51\C51\Lib
SET CPU_TYPE=N76E003
SET CPU_VENDOR=Nuvoton
SET UV2_TARGET=GPIO
SET CPU_XTAL=0x00F42400
"C:\Keil_v5\C51\C51\BIN\C51.EXE" @".\Output\GPIO.__i"
"C:\Keil_v5\C51\C51\BIN\C51.EXE" @".\Output\Delay.__i"
"C:\Keil_v5\C51\C51\BIN\C51.EXE" @".\Output\Common.__i"
"C:\Keil_v5\C51\C51\BIN\C51.EXE" @".\Output\iic_oled.__i"
"C:\Keil_v5\C51\C51\BIN\C51.EXE" @".\Output\HX711.__i"
"C:\Keil_v5\C51\C51\BIN\A51.EXE" @".\Output\STARTUP._ia"
"C:\Keil_v5\C51\C51\BIN\LX51.EXE" @".\Output\GPIO.lnp"
"C:\Keil_v5\C51\C51\BIN\OHX51.EXE" ".\Output\GPIO" HEX
